"use client"

import { useEffect, useMemo, useRef, useState } from "react"
import { useRouter } from "next/navigation"
import { ProtectedRoute } from "@/components/auth/ProtectedRoute"
import { DashboardSidebar } from "@/components/dashboard/DashboardSidebar"
import { DashboardHeader } from "@/components/dashboard/DashboardHeader"
import { Button } from "@/components/ui/button"
import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  Bell,
  Bold,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Italic,
  Link2,
  List,
  ListOrdered,
  MapPin,
  Paperclip,
  Plus,
  RefreshCcw,
  Redo2,
  Strikethrough,
  Subscript,
  Superscript,
  Underline,
  Unlink,
  UploadCloud,
  X,
  Eraser,
  Undo2,
} from "lucide-react"

type Event = {
  id: string
  title: string
  description?: string
  location?: string
  reminder?: Reminder
  type:
    | "rent_due"
    | "utility_bill_due"
    | "expense_payment"
    | "application_received"
    | "lease_start_end_renewal"
    | "payment_received"
    | "scheduled_repair"
    | "inspection"
    | "property_viewing"
    | "internal_reminder"
    | "internal_meeting"
    | "custom_tenant_event"
  startDate: Date
  endDate?: Date
  allDay?: boolean
  tenantId?: string
  unitId?: string
  isBuildingWide?: boolean
  status: "upcoming" | "completed" | "cancelled"
  priority: "low" | "medium" | "high"
  notifyByEmail?: boolean
  createdAt: Date
}

type Tenant = { id: string; name: string; email: string; unitId: string }
type Unit = { id: string; name: string }
type View = "month" | "week" | "day" | "list"
type Recurrence = "none" | "daily" | "weekly" | "monthly"
type Reminder = "none" | "10m" | "30m" | "1h" | "1d"
type CalendarEvent = Event & { recurrence?: Exclude<Recurrence, "none">; autoGenerated?: boolean }

const tenants: Tenant[] = [
  { id: "t1", name: "Mehret Getachew", email: "mehret.getachew@tenant.com", unitId: "u1" },
  { id: "t2", name: "John Anderson", email: "john.anderson@tenant.com", unitId: "u2" },
  { id: "t3", name: "Sarah Mitchell", email: "sarah.mitchell@tenant.com", unitId: "u3" },
]

const units: Unit[] = [
  { id: "u1", name: "A-101" },
  { id: "u2", name: "A-202" },
  { id: "u3", name: "B-305" },
]

const GOOGLE_CONNECTED_KEY = "bms.calendar.googleConnected"
const GOOGLE_LAST_SYNC_KEY = "bms.calendar.googleLastSync"

const eventTypeStyle: Record<Event["type"], { label: string; bg: string; text: string; border: string; category: "automatic" | "manual" }> = {
  rent_due: { label: "Rent Due", bg: "#FEF3C7", text: "#92400E", border: "#F59E0B", category: "automatic" },
  utility_bill_due: { label: "Utility Bill Due", bg: "#E0F2FE", text: "#0C4A6E", border: "#0284C7", category: "automatic" },
  expense_payment: { label: "Expense Payment", bg: "#F3E8FF", text: "#6B21A8", border: "#A855F7", category: "automatic" },
  application_received: { label: "Application Received", bg: "#DCFCE7", text: "#166534", border: "#22C55E", category: "automatic" },
  lease_start_end_renewal: { label: "Lease Start / End / Renewal", bg: "#FFE4E6", text: "#9F1239", border: "#F43F5E", category: "automatic" },
  payment_received: { label: "Payment Received", bg: "#D1FAE5", text: "#065F46", border: "#10B981", category: "automatic" },
  scheduled_repair: { label: "Scheduled Repair", bg: "#FEF2F2", text: "#991B1B", border: "#EF4444", category: "manual" },
  inspection: { label: "Inspection", bg: "#DBEAFE", text: "#1E3A8A", border: "#3B82F6", category: "manual" },
  property_viewing: { label: "Property Viewing", bg: "#ECFCCB", text: "#365314", border: "#84CC16", category: "manual" },
  internal_reminder: { label: "Internal Reminder", bg: "#F3F4F6", text: "#374151", border: "#9CA3AF", category: "manual" },
  internal_meeting: { label: "Internal Meeting", bg: "#EDE9FE", text: "#4C1D95", border: "#8B5CF6", category: "manual" },
  custom_tenant_event: { label: "Custom Tenant Event", bg: "#FFEDD5", text: "#9A3412", border: "#FB923C", category: "manual" },
}

const startDay = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate())
const dateKey = (d: Date) => startDay(d).toISOString().slice(0, 10)
const sameDay = (a: Date, b: Date) => dateKey(a) === dateKey(b)
const startWeek = (d: Date) => {
  const x = startDay(d)
  const wd = x.getDay()
  x.setDate(x.getDate() + (wd === 0 ? -6 : 1 - wd))
  return x
}
const weekDays = (d: Date) => Array.from({ length: 7 }, (_, i) => {
  const x = new Date(startWeek(d))
  x.setDate(x.getDate() + i)
  return x
})
const monthGrid = (d: Date) => Array.from({ length: 35 }, (_, i) => {
  const x = new Date(d.getFullYear(), d.getMonth(), 1)
  x.setDate(1 + i)
  return x
})
const toInput = (d: Date) => new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16)

const initialEvents: CalendarEvent[] = [
  {
    id: "evt-1",
    title: "Quarterly Building Inspection",
    type: "inspection",
    startDate: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() + 2, 14, 0),
    status: "upcoming",
    priority: "medium",
    createdAt: new Date(),
    isBuildingWide: true,
  },
  {
    id: "evt-2",
    title: "Renewal Meeting",
    type: "internal_meeting",
    startDate: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 16, 0),
    status: "upcoming",
    priority: "low",
    createdAt: new Date(),
    tenantId: "t1",
    unitId: "u1",
  },
]

function autoEvents(baseDate: Date): CalendarEvent[] {
  const monthStart = new Date(baseDate.getFullYear(), baseDate.getMonth(), 1, 9, 0)
  const thisYear = baseDate.getFullYear()
  const thisMonth = baseDate.getMonth()
  return [
    ...tenants.map((tenant, i) => ({
      id: `auto-rent-${tenant.id}`,
      title: `Rent Due - ${tenant.name}`,
      type: "rent_due" as const,
      startDate: new Date(monthStart.getFullYear(), monthStart.getMonth(), 1 + i, 9, 0),
      status: "upcoming" as const,
      priority: "high" as const,
      createdAt: new Date(),
      tenantId: tenant.id,
      unitId: units[i % units.length].id,
      recurrence: "monthly" as const,
      autoGenerated: true,
      description: "System generated",
    })),
    ...tenants.map((tenant, i) => ({
      id: `auto-utility-${tenant.id}`,
      title: `Utility Bill Due - ${tenant.name}`,
      type: "utility_bill_due" as const,
      startDate: new Date(thisYear, thisMonth, 5 + i, 10, 0),
      status: "upcoming" as const,
      priority: "high" as const,
      createdAt: new Date(),
      tenantId: tenant.id,
      unitId: units[i % units.length].id,
      recurrence: "monthly" as const,
      autoGenerated: true,
      description: "Auto from utility billing cycle",
    })),
    {
      id: "auto-expense",
      title: "Expense Payment - Security Services",
      type: "expense_payment",
      startDate: new Date(thisYear, thisMonth, 8, 11, 0),
      status: "upcoming",
      priority: "medium",
      createdAt: new Date(),
      isBuildingWide: true,
      recurrence: "monthly",
      autoGenerated: true,
      description: "Auto from expense schedule",
    },
    {
      id: "auto-application",
      title: "Application Received - Unit A-202",
      type: "application_received",
      startDate: new Date(thisYear, thisMonth, Math.max(2, baseDate.getDate() - 1), 13, 15),
      status: "upcoming",
      priority: "medium",
      createdAt: new Date(),
      unitId: "u2",
      autoGenerated: true,
      description: "Auto from application intake",
    },
    {
      id: "auto-lease",
      title: "Lease End / Renewal Window - A-202",
      type: "lease_start_end_renewal",
      startDate: new Date(baseDate.getFullYear(), baseDate.getMonth() + 1, 6, 10, 0),
      status: "upcoming",
      priority: "medium",
      createdAt: new Date(),
      tenantId: "t2",
      unitId: "u2",
      autoGenerated: true,
      description: "Auto from lease date",
    },
    {
      id: "auto-payment-received",
      title: "Payment Received - Mehret Getachew",
      type: "payment_received",
      startDate: new Date(baseDate.getFullYear(), baseDate.getMonth(), Math.max(1, baseDate.getDate() - 2), 15, 0),
      status: "upcoming",
      priority: "medium",
      createdAt: new Date(),
      tenantId: "t1",
      unitId: "u1",
      autoGenerated: true,
      description: "Auto from payment posting",
    },
  ]
}

function expandRecurring(events: CalendarEvent[], daysWindow = 120): CalendarEvent[] {
  const out: CalendarEvent[] = []
  const now = startDay(new Date())
  const end = new Date(now)
  end.setDate(end.getDate() + daysWindow)

  events.forEach((evt) => {
    if (!evt.recurrence) {
      out.push(evt)
      return
    }
    let cursor = new Date(evt.startDate)
    let guard = 0
    while (cursor <= end && guard < 200) {
      if (cursor >= now) {
        out.push({
          ...evt,
          id: `${evt.id}-${dateKey(cursor)}`,
          startDate: new Date(cursor),
        })
      }
      if (evt.recurrence === "daily") cursor.setDate(cursor.getDate() + 1)
      if (evt.recurrence === "weekly") cursor.setDate(cursor.getDate() + 7)
      if (evt.recurrence === "monthly") cursor.setMonth(cursor.getMonth() + 1)
      guard += 1
    }
  })
  return out
}

export default function CalendarPage() {
  return (
    <ProtectedRoute requiredRole="landlord">
      <CalendarContent />
    </ProtectedRoute>
  )
}

function CalendarContent() {
  const SIDEBAR_COLLAPSED_KEY = "bms.dashboard.sidebarCollapsed"
  const router = useRouter()
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(() => typeof window !== "undefined" && localStorage.getItem(SIDEBAR_COLLAPSED_KEY) === "true")
  const [view, setView] = useState<View>("month")
  const [focus, setFocus] = useState(new Date())
  const [selectedDate, setSelectedDate] = useState(startDay(new Date()))
  const [events, setEvents] = useState<CalendarEvent[]>(initialEvents)
  const [searchQuery, setSearchQuery] = useState("")
  const [openEditor, setOpenEditor] = useState(false)
  const [googleConnected, setGoogleConnected] = useState(() => typeof window !== "undefined" && localStorage.getItem(GOOGLE_CONNECTED_KEY) === "true")
  const [lastSyncedAt, setLastSyncedAt] = useState<string | null>(() => (typeof window !== "undefined" ? localStorage.getItem(GOOGLE_LAST_SYNC_KEY) : null))
  const [syncNotice, setSyncNotice] = useState<string | null>(null)
  const [tenantFilter] = useState<"all" | string>("all")
  const [unitFilter] = useState<"all" | string>("all")
  const [statusFilter] = useState<"all" | Event["status"]>("all")
  const [priorityFilter] = useState<"all" | Event["priority"]>("all")
  const [title, setTitle] = useState("")
  const [type, setType] = useState<Event["type"]>("internal_meeting")
  const [start, setStart] = useState(toInput(new Date()))
  const [location, setLocation] = useState("")
  const [reminder, setReminder] = useState<Reminder>("none")
  const [tenantId, setTenantId] = useState("")
  const [unitId, setUnitId] = useState("")
  const [status, setStatus] = useState<Event["status"]>("upcoming")
  const [priority, setPriority] = useState<Event["priority"]>("medium")
  const [notesHtml, setNotesHtml] = useState("")
  const [fontFamily, setFontFamily] = useState("sans-serif")
  const [fontSize, setFontSize] = useState("3")
  const [notifyByEmail, setNotifyByEmail] = useState(true)
  const [eventAttachments, setEventAttachments] = useState<File[]>([])
  const [isBuildingWide, setIsBuildingWide] = useState(false)
  const [recurrence, setRecurrence] = useState<Recurrence>("none")
  const detailsRef = useRef<HTMLDivElement | null>(null)
  const eventFileInputRef = useRef<HTMLInputElement | null>(null)

  useEffect(() => { localStorage.setItem(SIDEBAR_COLLAPSED_KEY, String(isSidebarCollapsed)) }, [isSidebarCollapsed])
  useEffect(() => { localStorage.setItem(GOOGLE_CONNECTED_KEY, String(googleConnected)) }, [googleConnected])
  useEffect(() => {
    if (!lastSyncedAt) {
      localStorage.removeItem(GOOGLE_LAST_SYNC_KEY)
      return
    }
    localStorage.setItem(GOOGLE_LAST_SYNC_KEY, lastSyncedAt)
  }, [lastSyncedAt])
  useEffect(() => {
    if (!syncNotice) return
    const timer = setTimeout(() => setSyncNotice(null), 2400)
    return () => clearTimeout(timer)
  }, [syncNotice])

  const mergedEvents = useMemo(() => expandRecurring([...events, ...autoEvents(focus)]), [events, focus])
  const filteredEvents = useMemo(() => mergedEvents
    .filter((e) => (tenantFilter === "all" ? true : e.tenantId === tenantFilter))
    .filter((e) => (unitFilter === "all" ? true : e.unitId === unitFilter))
    .filter((e) => (statusFilter === "all" ? true : e.status === statusFilter))
    .filter((e) => (priorityFilter === "all" ? true : e.priority === priorityFilter))
    .filter((e) => (!searchQuery.trim() ? true : `${e.title} ${e.description || ""}`.toLowerCase().includes(searchQuery.toLowerCase())))
    .sort((a, b) => a.startDate.getTime() - b.startDate.getTime()),
  [mergedEvents, tenantFilter, unitFilter, statusFilter, priorityFilter, searchQuery])

  const eventsByDay = useMemo(() => {
    const map = new Map<string, CalendarEvent[]>()
    filteredEvents.forEach((e) => map.set(dateKey(e.startDate), [...(map.get(dateKey(e.startDate)) || []), e]))
    return map
  }, [filteredEvents])

  const upcomingEvents = filteredEvents.filter((e) => e.startDate <= new Date(new Date().setDate(new Date().getDate() + 3)) && e.startDate >= startDay(new Date())).length

  const exec = (command: string, value?: string) => {
    detailsRef.current?.focus()
    document.execCommand(command, false, value)
    setNotesHtml(detailsRef.current?.innerHTML || "")
  }

  const handleDropFiles = (files: FileList | null) => {
    if (!files || files.length === 0) return
    const next = Array.from(files).slice(0, 10)
    setEventAttachments((prev) => [...prev, ...next].slice(0, 10))
  }

  const addEvent = () => {
    if (!title.trim()) return
    const descriptionText = (detailsRef.current?.innerText || notesHtml.replace(/<[^>]*>/g, " ")).trim()
    setEvents((prev) => [...prev, {
      id: `evt-${crypto.randomUUID()}`,
      title,
      description: descriptionText || undefined,
      location: location || undefined,
      reminder,
      type,
      startDate: new Date(start),
      tenantId: tenantId || undefined,
      unitId: unitId || undefined,
      status,
      priority,
      notifyByEmail,
      isBuildingWide,
      createdAt: new Date(),
      recurrence: recurrence === "none" ? undefined : recurrence,
    }])
    setTitle("")
    setLocation("")
    setReminder("none")
    setTenantId("")
    setUnitId("")
    setType("internal_meeting")
    setStatus("upcoming")
    setPriority("medium")
    setRecurrence("none")
    setIsBuildingWide(false)
    setNotifyByEmail(true)
    setEventAttachments([])
    setNotesHtml("")
    if (detailsRef.current) detailsRef.current.innerHTML = ""
    setOpenEditor(false)
  }

  const handleLogout = () => {
    localStorage.removeItem("isAuthenticated")
    localStorage.removeItem("userRole")
    localStorage.removeItem("authToken")
    document.cookie = "isAuthenticated=; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT"
    document.cookie = "userRole=; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT"
    document.cookie = "authToken=; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT"
    router.push("/auth/signin")
  }

  const connectGoogleCalendar = () => {
    setGoogleConnected(true)
    setSyncNotice("Google Calendar connected")
    window.open("https://calendar.google.com/calendar/u/0/r", "_blank", "noopener,noreferrer")
  }

  const syncGoogleCalendar = () => {
    if (!googleConnected) {
      connectGoogleCalendar()
      return
    }
    const now = new Date().toISOString()
    setLastSyncedAt(now)
    setSyncNotice("Calendar synced with Google")
  }

  const disconnectGoogle = () => {
    setGoogleConnected(false)
    setLastSyncedAt(null)
    setSyncNotice("Google Calendar disconnected")
  }

  return (
    <div className="min-h-screen flex bg-[#E9EDF3]">
      <DashboardSidebar isSidebarCollapsed={isSidebarCollapsed} onToggleSidebar={() => setIsSidebarCollapsed((x) => !x)} onLogout={handleLogout} appBrandName="BMS" />
      <div className="min-w-0 flex-1 flex flex-col">
        <DashboardHeader title="Calendar" subtitle="Calendar" searchQuery={searchQuery} onSearchChange={setSearchQuery} onToggleSidebar={() => setIsSidebarCollapsed((x) => !x)} />
        <main className="flex-1 overflow-y-auto p-2 md:p-3">
          <div className="mx-auto w-full max-w-none space-y-2.5">
            <div className="rounded-xl bg-white p-3 shadow-[0_8px_24px_rgba(31,53,73,0.08)] flex flex-wrap items-center justify-between gap-2.5">
              <div className="flex items-center gap-2">
                <Button variant="outline" onClick={() => setFocus(new Date(focus.getFullYear(), focus.getMonth() - 1, focus.getDate()))}><ChevronLeft className="h-4 w-4" /></Button>
                <Button variant="outline" onClick={() => setFocus(new Date())}>Today</Button>
                <Button variant="outline" onClick={() => setFocus(new Date(focus.getFullYear(), focus.getMonth() + 1, focus.getDate()))}><ChevronRight className="h-4 w-4" /></Button>
                <span className="ml-2 text-sm font-semibold text-slate-700">{focus.toLocaleString("en-US", { month: "long", year: "numeric" })}</span>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                {(["month", "week", "day", "list"] as View[]).map((v) => <button key={v} onClick={() => setView(v)} className={`rounded-lg px-3 py-2 text-xs font-semibold uppercase ${view === v ? "bg-[#3096DA] text-white" : "bg-slate-100 text-slate-600"}`}>{v}</button>)}
                {!googleConnected ? (
                  <Button className="bg-[#3096DA] text-white hover:bg-[#277FB8]" onClick={connectGoogleCalendar}>
                    <Link2 className="mr-1.5 h-4 w-4" />Connect Google Calendar
                  </Button>
                ) : (
                  <>
                    <Button variant="outline" onClick={syncGoogleCalendar}><RefreshCcw className="mr-1.5 h-4 w-4" />Sync Google</Button>
                    <Button variant="outline" onClick={disconnectGoogle}><Unlink className="mr-1.5 h-4 w-4" />Disconnect</Button>
                  </>
                )}
                <Button className="bg-[#3096DA] text-white hover:bg-[#277FB8]" onClick={() => setOpenEditor(true)}><Plus className="mr-1.5 h-4 w-4" />Add Event</Button>
                <div className="rounded-full bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-700 inline-flex items-center gap-1.5"><CalendarDays className="h-4 w-4 text-[#3096DA]" />{upcomingEvents}</div>
              </div>
              {lastSyncedAt && <div className="w-full text-xs text-slate-500">Last synced: {new Date(lastSyncedAt).toLocaleString()}</div>}
            </div>

            <div className="grid grid-cols-1 gap-2">
              <section className="rounded-xl bg-white p-2.5 shadow-[0_8px_24px_rgba(31,53,73,0.08)]">
                {view === "month" && (
                  <div className="grid grid-cols-7 gap-2">
                    {["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((d) => <div key={d} className="text-[11px] uppercase font-bold text-slate-500 px-1">{d}</div>)}
                    {monthGrid(focus).map((d) => {
                      const list = eventsByDay.get(dateKey(d)) || []
                      return (
                        <div key={dateKey(d)} onClick={() => setSelectedDate(d)} onDragOver={(e) => e.preventDefault()} onDrop={(e) => {
                          const movedId = e.dataTransfer.getData("event-id")
                          if (movedId) setEvents((prev) => prev.map((x) => x.id === movedId ? { ...x, startDate: new Date(d.getFullYear(), d.getMonth(), d.getDate(), x.startDate.getHours(), x.startDate.getMinutes()) } : x))
                        }} className={`min-h-[96px] rounded-xl border p-1.5 ${d.getMonth() === focus.getMonth() ? "border-slate-200" : "border-slate-100 bg-slate-50"}`}>
                          <div className="flex items-center justify-between">
                            <span
                              className={`inline-flex h-7 w-7 items-center justify-center rounded-full text-xs font-semibold ${
                                sameDay(d, new Date())
                                  ? "border-2 border-emerald-500 bg-emerald-50 text-emerald-700"
                                  : "text-slate-600"
                              }`}
                            >
                              {d.getDate()}
                            </span>
                            <button onClick={(e) => { e.stopPropagation(); setSelectedDate(d); setOpenEditor(true) }} className="h-5 w-5 rounded bg-slate-100 text-slate-600 inline-flex items-center justify-center"><Plus className="h-3.5 w-3.5" /></button>
                          </div>
                          <div className="space-y-1 mt-1">
                            {list.slice(0, 3).map((e) => (
                              <div
                                key={e.id}
                                draggable={!e.autoGenerated}
                                onDragStart={(de) => de.dataTransfer.setData("event-id", e.id)}
                                className="w-full truncate rounded border px-2 py-1 text-left text-[10px] font-semibold"
                                style={{
                                  backgroundColor: eventTypeStyle[e.type].bg,
                                  borderColor: eventTypeStyle[e.type].border,
                                  color: eventTypeStyle[e.type].text,
                                }}
                              >
                                {e.title}
                              </div>
                            ))}
                            {list.length > 3 && <div className="text-[10px] text-slate-500">+{list.length - 3} more</div>}
                          </div>
                        </div>
                      )
                    })}
                  </div>
                )}
                {view !== "month" && (
                  <div className="space-y-2">
                    {(view === "week" ? weekDays(focus).flatMap((d) => eventsByDay.get(dateKey(d)) || []) : view === "day" ? (eventsByDay.get(dateKey(focus)) || []) : filteredEvents).length === 0 ? (
                      <div className="rounded-xl border border-slate-200 p-4 text-sm text-slate-500">
                        {view === "week" ? "No event for this week" : view === "day" ? "No event for this day" : "No events found"}
                      </div>
                    ) : (view === "week" ? weekDays(focus).flatMap((d) => eventsByDay.get(dateKey(d)) || []) : view === "day" ? (eventsByDay.get(dateKey(focus)) || []) : filteredEvents).map((e) => (
                      <div key={e.id} className="w-full rounded-xl border border-slate-200 p-3 text-left">
                        <div className="flex items-start justify-between gap-2">
                          <div className="text-sm font-semibold text-slate-800">{e.title}</div>
                          <span
                            className="inline-flex rounded-full border px-2 py-0.5 text-[10px] font-semibold"
                            style={{
                              backgroundColor: eventTypeStyle[e.type].bg,
                              borderColor: eventTypeStyle[e.type].border,
                              color: eventTypeStyle[e.type].text,
                            }}
                          >
                            {eventTypeStyle[e.type].label}
                          </span>
                        </div>
                        <div className="text-xs text-slate-500 mt-1">{e.startDate.toLocaleString()}</div>
                      </div>
                    ))}
                  </div>
                )}
              </section>
            </div>
          </div>
        </main>
      </div>

      {openEditor && (
        <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/30 p-3 md:p-4">
          <div className="mx-auto mt-2 mb-4 w-full max-w-[760px] rounded-2xl bg-white shadow-2xl border border-slate-200">
            <div className="flex items-center justify-between bg-[#ECEDEF] px-5 py-4 border-b border-slate-200 rounded-t-2xl">
              <div className="text-[1.6rem] font-medium text-slate-800 leading-none">Create event</div>
              <button type="button" onClick={() => setOpenEditor(false)} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-500 hover:bg-slate-200 hover:text-slate-700">
                <X className="h-5 w-5" />
              </button>
            </div>
            <div className="max-h-[calc(100vh-190px)] overflow-y-auto">
              <div className="space-y-3 p-5">
                <EditorField label="Title"><input className="h-9 w-full max-w-[380px] rounded-xl border border-slate-300 px-3 text-sm" value={title} onChange={(e) => setTitle(e.target.value)} /></EditorField>
                <EditorField label="Date & Time"><input type="datetime-local" className="h-9 w-full max-w-[380px] rounded-xl border border-slate-300 px-3 text-sm" value={start} onChange={(e) => setStart(e.target.value)} /></EditorField>
                <EditorField label="Location">
                  <div className="relative max-w-[380px]">
                    <MapPin className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                    <input className="h-9 w-full rounded-xl border border-slate-300 pl-9 pr-3 text-sm" placeholder="Add location" value={location} onChange={(e) => setLocation(e.target.value)} />
                  </div>
                </EditorField>
                <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                  <EditorField label="Reminder">
                    <div className="relative max-w-[320px]">
                      <Bell className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                      <div className="relative">
                        <select className="h-9 w-full appearance-none rounded-xl border border-slate-300 bg-white pl-9 pr-12 text-sm" value={reminder} onChange={(e) => setReminder(e.target.value as Reminder)}>
                          <option value="none">None</option>
                          <option value="10m">10 minutes before</option>
                          <option value="30m">30 minutes before</option>
                          <option value="1h">1 hour before</option>
                          <option value="1d">1 day before</option>
                        </select>
                        <ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
                      </div>
                    </div>
                  </EditorField>
                  <EditorField label="Event Type">
                    <div className="relative max-w-[320px]">
                      <select
                        className="h-9 w-full appearance-none rounded-xl border border-slate-300 bg-white px-3 pr-12 text-sm"
                        value={type}
                        onChange={(e) => setType(e.target.value as Event["type"])}
                      >
                        <optgroup label="Manual Events">
                          {Object.entries(eventTypeStyle)
                            .filter(([, meta]) => meta.category === "manual")
                            .map(([key, meta]) => (
                              <option key={key} value={key}>
                                {meta.label}
                              </option>
                            ))}
                        </optgroup>
                        <optgroup label="Automatic Events">
                          {Object.entries(eventTypeStyle)
                            .filter(([, meta]) => meta.category === "automatic")
                            .map(([key, meta]) => (
                              <option key={key} value={key}>
                                {meta.label}
                              </option>
                            ))}
                        </optgroup>
                      </select>
                      <ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
                    </div>
                  </EditorField>
                  <EditorField label="Tenant"><div className="relative max-w-[320px]"><select className="h-9 w-full appearance-none rounded-xl border border-slate-300 px-3 pr-12 text-sm" value={tenantId} onChange={(e) => setTenantId(e.target.value)}><option value="">None</option>{tenants.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /></div></EditorField>
                  <EditorField label="Unit"><div className="relative max-w-[320px]"><select className="h-9 w-full appearance-none rounded-xl border border-slate-300 px-3 pr-12 text-sm" value={unitId} onChange={(e) => setUnitId(e.target.value)}><option value="">None</option>{units.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /></div></EditorField>
                  <EditorField label="Status"><div className="relative max-w-[320px]"><select className="h-9 w-full appearance-none rounded-xl border border-slate-300 px-3 pr-12 text-sm" value={status} onChange={(e) => setStatus(e.target.value as Event["status"])}>{["upcoming", "completed", "cancelled"].map((x) => <option key={x} value={x}>{x}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /></div></EditorField>
                  <EditorField label="Priority"><div className="relative max-w-[320px]"><select className="h-9 w-full appearance-none rounded-xl border border-slate-300 px-3 pr-12 text-sm" value={priority} onChange={(e) => setPriority(e.target.value as Event["priority"])}>{["low", "medium", "high"].map((x) => <option key={x} value={x}>{x}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /></div></EditorField>
                  <EditorField label="Recurring"><div className="relative max-w-[320px]"><select className="h-9 w-full appearance-none rounded-xl border border-slate-300 px-3 pr-12 text-sm" value={recurrence} onChange={(e) => setRecurrence(e.target.value as Recurrence)}>{["none", "daily", "weekly", "monthly"].map((x) => <option key={x} value={x}>{x}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /></div></EditorField>
                </div>
                <div className="flex items-end pb-1"><label className="inline-flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={isBuildingWide} onChange={(e) => setIsBuildingWide(e.target.checked)} />Applies to whole building</label></div>
                <EditorField label="Details" fullWidth>
                  <div className="rounded-xl border border-slate-300">
                    <div className="flex flex-wrap items-center gap-1 border-b border-slate-200 p-2">
                      <select value={fontFamily} onChange={(e) => { setFontFamily(e.target.value); exec("fontName", e.target.value) }} className="h-8 w-[140px] rounded-md border border-slate-300 bg-white px-2 text-sm">
                        <option value="sans-serif">sans-serif</option>
                        <option value="serif">serif</option>
                        <option value="monospace">monospace</option>
                        <option value="Arial">Arial</option>
                      </select>
                      <select value={fontSize} onChange={(e) => { setFontSize(e.target.value); exec("fontSize", e.target.value) }} className="h-8 w-[88px] rounded-md border border-slate-300 bg-white px-2 text-sm">
                        <option value="1">8pt</option>
                        <option value="2">10pt</option>
                        <option value="3">12pt</option>
                        <option value="4">14pt</option>
                        <option value="5">18pt</option>
                      </select>
                      <button type="button" onClick={() => exec("bold")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><Bold className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("italic")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><Italic className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("underline")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><Underline className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("strikeThrough")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><Strikethrough className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("justifyLeft")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><AlignLeft className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("justifyCenter")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><AlignCenter className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("justifyRight")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><AlignRight className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("insertUnorderedList")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><List className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("insertOrderedList")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><ListOrdered className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("subscript")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><Subscript className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("superscript")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><Superscript className="h-4 w-4" /></button>
                      <button type="button" onClick={() => { const url = window.prompt("Enter URL"); if (url) exec("createLink", url) }} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><Link2 className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("removeFormat")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><Eraser className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("undo")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><Undo2 className="h-4 w-4" /></button>
                      <button type="button" onClick={() => exec("redo")} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-600 hover:bg-slate-100"><Redo2 className="h-4 w-4" /></button>
                    </div>
                    <div
                      ref={detailsRef}
                      contentEditable
                      suppressContentEditableWarning
                      onInput={(e) => setNotesHtml(e.currentTarget.innerHTML)}
                      className="min-h-[190px] w-full rounded-b-xl px-3 py-2 text-sm outline-none"
                      style={{ fontFamily }}
                      data-placeholder="Add center paragraph and event details..."
                    />
                  </div>
                </EditorField>
                <div className="border-t border-slate-200 pt-4">
                  <div className="mb-2 text-[0.68rem] font-semibold uppercase tracking-[0.08em] text-slate-500">Attachments</div>
                  <div
                    className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center"
                    onDragOver={(e) => e.preventDefault()}
                    onDrop={(e) => {
                      e.preventDefault()
                      handleDropFiles(e.dataTransfer.files)
                    }}
                  >
                    <UploadCloud className="mx-auto h-8 w-8 text-slate-400" />
                    <p className="mt-2 text-sm font-medium text-slate-700">Drag and drop files here or browse files</p>
                    <p className="mt-1 text-xs text-slate-500">Limited to 10 files. Max file size is 20MB.</p>
                    <button type="button" onClick={() => eventFileInputRef.current?.click()} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-700 hover:bg-slate-100">
                      <Paperclip className="h-4 w-4" />
                      Browse Files
                    </button>
                    <input ref={eventFileInputRef} type="file" multiple className="hidden" onChange={(e) => handleDropFiles(e.target.files)} />
                    {eventAttachments.length > 0 && (
                      <div className="mt-3 space-y-1 text-left">
                        {eventAttachments.map((file, i) => (
                          <div key={`${file.name}-${i}`} className="truncate rounded-md border border-slate-200 bg-white px-2 py-1 text-xs text-slate-700">{file.name}</div>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
                <div className="border-t border-slate-200 pt-4">
                  <div className="mb-1 text-lg font-semibold text-slate-800">Notifications</div>
                  <p className="mb-3 text-sm text-slate-500">Keep residents informed by telling them what changed.</p>
                  <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700 space-y-2">
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input type="checkbox" checked={notifyByEmail} onChange={(e) => setNotifyByEmail(e.target.checked)} />
                      An email update for this event
                    </label>
                    <div className="flex items-center gap-2">
                      <Check className="h-4 w-4 text-emerald-600" />
                      Push notifications through the mobile app
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="sticky bottom-0 px-5 py-4 border-t border-slate-200 flex justify-end gap-2 bg-white rounded-b-2xl">
              <Button variant="outline" onClick={() => setOpenEditor(false)}>Cancel</Button>
              <Button className="bg-[#3096DA] text-white hover:bg-[#277FB8]" onClick={addEvent}>Create</Button>
            </div>
          </div>
        </div>
      )}

      {syncNotice && (
        <div className="fixed top-5 right-5 z-[80] rounded-lg bg-[#1F3549] px-3 py-2 text-sm font-semibold text-white shadow-lg">
          {syncNotice}
        </div>
      )}
    </div>
  )
}

function EditorField({ label, children, fullWidth = false }: { label: string; children: React.ReactNode; fullWidth?: boolean }) {
  return (
    <label className={`block ${fullWidth ? "" : "max-w-[380px]"}`}>
      <span className="mb-1 block text-[0.68rem] font-semibold uppercase tracking-[0.08em] text-slate-500">{label}</span>
      {children}
    </label>
  )
}

