"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { ProtectedRoute } from "@/components/auth/ProtectedRoute"
import { DashboardSidebar } from "@/components/dashboard/DashboardSidebar"
import { DashboardHeader } from "@/components/dashboard/DashboardHeader"
import { Button } from "@/components/ui/button"
import { CalendarDays, ChevronLeft, ChevronRight, Plus } from "lucide-react"

type Event = {
  id: string
  title: string
  description?: string
  type: "maintenance" | "payment" | "inspection" | "meeting" | "notice" | "lease"
  startDate: Date
  endDate?: Date
  allDay?: boolean
  tenantId?: string
  unitId?: string
  isBuildingWide?: boolean
  status: "upcoming" | "completed" | "cancelled"
  priority: "low" | "medium" | "high"
  createdAt: Date
}

type Tenant = { id: string; name: string }
type Unit = { id: string; name: string }
type View = "month" | "week" | "day" | "list"
type Recurrence = "none" | "daily" | "weekly" | "monthly"
type CalendarEvent = Event & { recurrence?: Exclude<Recurrence, "none">; autoGenerated?: boolean }

const tenants: Tenant[] = [
  { id: "t1", name: "Lily Smith" },
  { id: "t2", name: "John Anderson" },
  { id: "t3", name: "Sarah Mitchell" },
]

const units: Unit[] = [
  { id: "u1", name: "A-101" },
  { id: "u2", name: "A-202" },
  { id: "u3", name: "B-305" },
]

const eventTypeColor: Record<Event["type"], string> = {
  maintenance: "#F59E0B",
  payment: "#10B981",
  inspection: "#3B82F6",
  meeting: "#8B5CF6",
  notice: "#EF4444",
  lease: "#EAB308",
}

const startDay = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate())
const dateKey = (d: Date) => startDay(d).toISOString().slice(0, 10)
const sameDay = (a: Date, b: Date) => dateKey(a) === dateKey(b)
const startWeek = (d: Date) => {
  const x = startDay(d)
  const wd = x.getDay()
  x.setDate(x.getDate() + (wd === 0 ? -6 : 1 - wd))
  return x
}
const weekDays = (d: Date) => Array.from({ length: 7 }, (_, i) => {
  const x = new Date(startWeek(d))
  x.setDate(x.getDate() + i)
  return x
})
const monthGrid = (d: Date) => Array.from({ length: 42 }, (_, i) => {
  const x = new Date(startWeek(new Date(d.getFullYear(), d.getMonth(), 1)))
  x.setDate(x.getDate() + i)
  return x
})
const toInput = (d: Date) => new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16)

const initialEvents: CalendarEvent[] = [
  {
    id: "evt-1",
    title: "Quarterly Building Inspection",
    type: "inspection",
    startDate: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() + 2, 14, 0),
    status: "upcoming",
    priority: "medium",
    createdAt: new Date(),
    isBuildingWide: true,
  },
  {
    id: "evt-2",
    title: "Renewal Meeting",
    type: "meeting",
    startDate: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 16, 0),
    status: "upcoming",
    priority: "low",
    createdAt: new Date(),
    tenantId: "t1",
    unitId: "u1",
  },
]

function autoEvents(baseDate: Date): CalendarEvent[] {
  const monthStart = new Date(baseDate.getFullYear(), baseDate.getMonth(), 1, 9, 0)
  return [
    ...tenants.map((tenant, i) => ({
      id: `auto-rent-${tenant.id}`,
      title: `Rent Due - ${tenant.name}`,
      type: "payment" as const,
      startDate: new Date(monthStart.getFullYear(), monthStart.getMonth(), 1 + i, 9, 0),
      status: "upcoming" as const,
      priority: "high" as const,
      createdAt: new Date(),
      tenantId: tenant.id,
      unitId: units[i % units.length].id,
      recurrence: "monthly" as const,
      autoGenerated: true,
      description: "System generated",
    })),
    {
      id: "auto-lease",
      title: "Lease Expiry - A-202",
      type: "lease",
      startDate: new Date(baseDate.getFullYear(), baseDate.getMonth() + 1, 6, 10, 0),
      status: "upcoming",
      priority: "medium",
      createdAt: new Date(),
      tenantId: "t2",
      unitId: "u2",
      autoGenerated: true,
      description: "Auto from lease date",
    },
    {
      id: "auto-maintenance",
      title: "Maintenance Request - Plumbing",
      type: "maintenance",
      startDate: new Date(baseDate.getFullYear(), baseDate.getMonth(), baseDate.getDate() + 1, 11, 0),
      status: "upcoming",
      priority: "high",
      createdAt: new Date(),
      tenantId: "t3",
      unitId: "u3",
      autoGenerated: true,
      description: "Auto from request",
    },
  ]
}

function expandRecurring(events: CalendarEvent[], daysWindow = 120): CalendarEvent[] {
  const out: CalendarEvent[] = []
  const now = startDay(new Date())
  const end = new Date(now)
  end.setDate(end.getDate() + daysWindow)

  events.forEach((evt) => {
    if (!evt.recurrence) {
      out.push(evt)
      return
    }
    let cursor = new Date(evt.startDate)
    let guard = 0
    while (cursor <= end && guard < 200) {
      if (cursor >= now) {
        out.push({
          ...evt,
          id: `${evt.id}-${dateKey(cursor)}`,
          startDate: new Date(cursor),
        })
      }
      if (evt.recurrence === "daily") cursor.setDate(cursor.getDate() + 1)
      if (evt.recurrence === "weekly") cursor.setDate(cursor.getDate() + 7)
      if (evt.recurrence === "monthly") cursor.setMonth(cursor.getMonth() + 1)
      guard += 1
    }
  })
  return out
}

export default function CalendarPage() {
  return (
    <ProtectedRoute requiredRole="landlord">
      <CalendarContent />
    </ProtectedRoute>
  )
}

function CalendarContent() {
  const SIDEBAR_COLLAPSED_KEY = "bms.dashboard.sidebarCollapsed"
  const router = useRouter()
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(() => typeof window !== "undefined" && localStorage.getItem(SIDEBAR_COLLAPSED_KEY) === "true")
  const [view, setView] = useState<View>("month")
  const [focus, setFocus] = useState(new Date())
  const [selectedDate, setSelectedDate] = useState(startDay(new Date()))
  const [events, setEvents] = useState<CalendarEvent[]>(initialEvents)
  const [searchQuery, setSearchQuery] = useState("")
  const [openEditor, setOpenEditor] = useState(false)
  const [detailId, setDetailId] = useState<string | null>(null)
  const [eventTypeFilter, setEventTypeFilter] = useState<"all" | Event["type"]>("all")
  const [tenantFilter, setTenantFilter] = useState<"all" | string>("all")
  const [unitFilter, setUnitFilter] = useState<"all" | string>("all")
  const [statusFilter, setStatusFilter] = useState<"all" | Event["status"]>("all")
  const [priorityFilter, setPriorityFilter] = useState<"all" | Event["priority"]>("all")
  const [title, setTitle] = useState("")
  const [type, setType] = useState<Event["type"]>("meeting")
  const [start, setStart] = useState(toInput(new Date()))
  const [tenantId, setTenantId] = useState("")
  const [unitId, setUnitId] = useState("")
  const [status, setStatus] = useState<Event["status"]>("upcoming")
  const [priority, setPriority] = useState<Event["priority"]>("medium")
  const [notes, setNotes] = useState("")
  const [isBuildingWide, setIsBuildingWide] = useState(false)
  const [recurrence, setRecurrence] = useState<Recurrence>("none")

  useEffect(() => { localStorage.setItem(SIDEBAR_COLLAPSED_KEY, String(isSidebarCollapsed)) }, [isSidebarCollapsed])

  const mergedEvents = useMemo(() => expandRecurring([...events, ...autoEvents(focus)]), [events, focus])
  const filteredEvents = useMemo(() => mergedEvents
    .filter((e) => (eventTypeFilter === "all" ? true : e.type === eventTypeFilter))
    .filter((e) => (tenantFilter === "all" ? true : e.tenantId === tenantFilter))
    .filter((e) => (unitFilter === "all" ? true : e.unitId === unitFilter))
    .filter((e) => (statusFilter === "all" ? true : e.status === statusFilter))
    .filter((e) => (priorityFilter === "all" ? true : e.priority === priorityFilter))
    .filter((e) => (!searchQuery.trim() ? true : `${e.title} ${e.description || ""}`.toLowerCase().includes(searchQuery.toLowerCase())))
    .sort((a, b) => a.startDate.getTime() - b.startDate.getTime()),
  [mergedEvents, eventTypeFilter, tenantFilter, unitFilter, statusFilter, priorityFilter, searchQuery])

  const eventsByDay = useMemo(() => {
    const map = new Map<string, CalendarEvent[]>()
    filteredEvents.forEach((e) => map.set(dateKey(e.startDate), [...(map.get(dateKey(e.startDate)) || []), e]))
    return map
  }, [filteredEvents])

  const selectedEvents = filteredEvents.filter((e) => sameDay(e.startDate, selectedDate))
  const detailEvent = filteredEvents.find((e) => e.id === detailId) || null
  const todayEvents = filteredEvents.filter((e) => sameDay(e.startDate, new Date())).length
  const upcomingEvents = filteredEvents.filter((e) => e.startDate <= new Date(new Date().setDate(new Date().getDate() + 3)) && e.startDate >= startDay(new Date())).length
  const urgentEvents = filteredEvents.filter((e) => e.status === "upcoming" && e.priority === "high").length

  const addEvent = () => {
    if (!title.trim()) return
    setEvents((prev) => [...prev, {
      id: `evt-${crypto.randomUUID()}`,
      title,
      description: notes || undefined,
      type,
      startDate: new Date(start),
      tenantId: tenantId || undefined,
      unitId: unitId || undefined,
      status,
      priority,
      isBuildingWide,
      createdAt: new Date(),
      recurrence: recurrence === "none" ? undefined : recurrence,
    }])
    setOpenEditor(false)
  }

  return (
    <div className="min-h-screen flex bg-[#E9EDF3]">
      <DashboardSidebar isSidebarCollapsed={isSidebarCollapsed} onToggleSidebar={() => setIsSidebarCollapsed((x) => !x)} onLogout={() => { localStorage.clear(); router.push("/auth/signin") }} appBrandName="BMS" />
      <div className="min-w-0 flex-1 flex flex-col">
        <DashboardHeader title="Calendar" subtitle="Calendar management" searchQuery={searchQuery} onSearchChange={setSearchQuery} onToggleSidebar={() => setIsSidebarCollapsed((x) => !x)} />
        <main className="flex-1 overflow-y-auto p-5">
          <div className="mx-auto max-w-[1500px] space-y-4">
            <div className="rounded-2xl bg-white p-4 shadow-[0_8px_24px_rgba(31,53,73,0.08)] flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <Button variant="outline" onClick={() => setFocus(new Date(focus.getFullYear(), focus.getMonth() - 1, focus.getDate()))}><ChevronLeft className="h-4 w-4" /></Button>
                <Button variant="outline" onClick={() => setFocus(new Date())}>Today</Button>
                <Button variant="outline" onClick={() => setFocus(new Date(focus.getFullYear(), focus.getMonth() + 1, focus.getDate()))}><ChevronRight className="h-4 w-4" /></Button>
                <span className="ml-2 text-sm font-semibold text-slate-700">{focus.toLocaleString("en-US", { month: "long", year: "numeric" })}</span>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                {(["month", "week", "day", "list"] as View[]).map((v) => <button key={v} onClick={() => setView(v)} className={`rounded-lg px-3 py-2 text-xs font-semibold uppercase ${view === v ? "bg-[#3096DA] text-white" : "bg-slate-100 text-slate-600"}`}>{v}</button>)}
                <Button className="bg-[#3096DA] text-white hover:bg-[#277FB8]" onClick={() => setOpenEditor(true)}><Plus className="mr-1.5 h-4 w-4" />Add Event</Button>
                <div className="rounded-full bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-700 inline-flex items-center gap-1.5"><CalendarDays className="h-4 w-4 text-[#3096DA]" />{upcomingEvents}</div>
              </div>
            </div>

            <div className="grid grid-cols-1 xl:grid-cols-[260px_minmax(0,1fr)_320px] gap-4">
              <aside className="rounded-2xl bg-white p-4 space-y-3 shadow-[0_8px_24px_rgba(31,53,73,0.08)]">
                <Filter label="Type" value={eventTypeFilter} onChange={(v) => setEventTypeFilter(v as "all" | Event["type"])} options={["all", "maintenance", "payment", "inspection", "meeting", "notice", "lease"]} />
                <Filter label="Tenant" value={tenantFilter} onChange={setTenantFilter} options={["all", ...tenants.map((t) => t.id)]} />
                <Filter label="Unit" value={unitFilter} onChange={setUnitFilter} options={["all", ...units.map((u) => u.id)]} />
                <Filter label="Status" value={statusFilter} onChange={(v) => setStatusFilter(v as "all" | Event["status"])} options={["all", "upcoming", "completed", "cancelled"]} />
                <Filter label="Priority" value={priorityFilter} onChange={(v) => setPriorityFilter(v as "all" | Event["priority"])} options={["all", "low", "medium", "high"]} />
              </aside>

              <section className="rounded-2xl bg-white p-4 shadow-[0_8px_24px_rgba(31,53,73,0.08)]">
                {view === "month" && (
                  <div className="grid grid-cols-7 gap-2">
                    {["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((d) => <div key={d} className="text-[11px] uppercase font-bold text-slate-500 px-1">{d}</div>)}
                    {monthGrid(focus).map((d) => {
                      const list = eventsByDay.get(dateKey(d)) || []
                      return (
                        <div key={dateKey(d)} onClick={() => setSelectedDate(d)} onDragOver={(e) => e.preventDefault()} onDrop={(e) => {
                          const movedId = e.dataTransfer.getData("event-id")
                          if (movedId) setEvents((prev) => prev.map((x) => x.id === movedId ? { ...x, startDate: new Date(d.getFullYear(), d.getMonth(), d.getDate(), x.startDate.getHours(), x.startDate.getMinutes()) } : x))
                        }} className={`min-h-[110px] rounded-xl border p-2 ${d.getMonth() === focus.getMonth() ? "border-slate-200" : "border-slate-100 bg-slate-50"}`}>
                          <div className="flex items-center justify-between">
                            <span className={`text-xs font-semibold ${sameDay(d, new Date()) ? "text-[#3096DA]" : "text-slate-600"}`}>{d.getDate()}</span>
                            <button onClick={(e) => { e.stopPropagation(); setSelectedDate(d); setOpenEditor(true) }} className="h-5 w-5 rounded bg-slate-100 text-slate-600 inline-flex items-center justify-center"><Plus className="h-3.5 w-3.5" /></button>
                          </div>
                          <div className="space-y-1 mt-1">
                            {list.slice(0, 3).map((e) => (
                              <button key={e.id} draggable={!e.autoGenerated} onDragStart={(de) => de.dataTransfer.setData("event-id", e.id)} title={`${e.title}${e.description ? ` - ${e.description}` : ""}`} onClick={(ev) => { ev.stopPropagation(); setDetailId(e.id) }} className="w-full truncate rounded px-2 py-1 text-left text-[10px] font-medium text-white" style={{ backgroundColor: eventTypeColor[e.type] }}>
                                {e.title}
                              </button>
                            ))}
                            {list.length > 3 && <div className="text-[10px] text-slate-500">+{list.length - 3} more</div>}
                          </div>
                        </div>
                      )
                    })}
                  </div>
                )}
                {view !== "month" && (
                  <div className="space-y-2">
                    {(view === "week" ? weekDays(focus).flatMap((d) => eventsByDay.get(dateKey(d)) || []) : view === "day" ? (eventsByDay.get(dateKey(focus)) || []) : filteredEvents).map((e) => (
                      <button key={e.id} onClick={() => setDetailId(e.id)} className="w-full rounded-xl border border-slate-200 p-3 text-left">
                        <div className="text-sm font-semibold text-slate-800">{e.title}</div>
                        <div className="text-xs text-slate-500 mt-1">{e.startDate.toLocaleString()} • {e.type}</div>
                      </button>
                    ))}
                  </div>
                )}
              </section>

              <aside className="space-y-4">
                <Widget title="Today's events" value={todayEvents} />
                <Widget title="Upcoming events" value={upcomingEvents} />
                <Widget title="Urgent events" value={urgentEvents} />
                <div className="rounded-2xl bg-white p-4 shadow-[0_8px_24px_rgba(31,53,73,0.08)]">
                  <div className="text-xs font-bold uppercase tracking-[0.08em] text-slate-600">Selected Date</div>
                  <div className="mt-2 text-sm font-semibold text-slate-700">{selectedDate.toLocaleDateString()}</div>
                  <div className="mt-2 space-y-2">
                    {selectedEvents.map((e) => <button key={e.id} onClick={() => setDetailId(e.id)} className="w-full rounded-lg border border-slate-200 p-2 text-left text-xs font-semibold text-slate-700">{e.title}</button>)}
                    {selectedEvents.length === 0 && <div className="text-xs text-slate-500">No events</div>}
                  </div>
                </div>
              </aside>
            </div>
          </div>
        </main>
      </div>

      {openEditor && (
        <div className="fixed inset-0 z-50 bg-slate-900/30 p-4">
          <div className="mx-auto mt-10 max-w-2xl rounded-2xl bg-white shadow-2xl border border-slate-200">
            <div className="px-5 py-4 border-b border-slate-200 text-sm font-bold uppercase tracking-[0.06em] text-slate-700">Create / Edit Event</div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 p-5">
              <EditorField label="Title"><input className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" value={title} onChange={(e) => setTitle(e.target.value)} /></EditorField>
              <EditorField label="Type"><select className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" value={type} onChange={(e) => setType(e.target.value as Event["type"])}>{["maintenance", "payment", "inspection", "meeting", "notice", "lease"].map((x) => <option key={x} value={x}>{x}</option>)}</select></EditorField>
              <EditorField label="Date & Time"><input type="datetime-local" className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" value={start} onChange={(e) => setStart(e.target.value)} /></EditorField>
              <EditorField label="Tenant"><select className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" value={tenantId} onChange={(e) => setTenantId(e.target.value)}><option value="">None</option>{tenants.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></EditorField>
              <EditorField label="Unit"><select className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" value={unitId} onChange={(e) => setUnitId(e.target.value)}><option value="">None</option>{units.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></EditorField>
              <EditorField label="Status"><select className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" value={status} onChange={(e) => setStatus(e.target.value as Event["status"])}>{["upcoming", "completed", "cancelled"].map((x) => <option key={x} value={x}>{x}</option>)}</select></EditorField>
              <EditorField label="Priority"><select className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" value={priority} onChange={(e) => setPriority(e.target.value as Event["priority"])}>{["low", "medium", "high"].map((x) => <option key={x} value={x}>{x}</option>)}</select></EditorField>
              <EditorField label="Recurring"><select className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" value={recurrence} onChange={(e) => setRecurrence(e.target.value as Recurrence)}>{["none", "daily", "weekly", "monthly"].map((x) => <option key={x} value={x}>{x}</option>)}</select></EditorField>
              <div className="flex items-end pb-2"><label className="inline-flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={isBuildingWide} onChange={(e) => setIsBuildingWide(e.target.checked)} />Applies to whole building</label></div>
              <EditorField label="Notes"><textarea className="min-h-[88px] w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" value={notes} onChange={(e) => setNotes(e.target.value)} /></EditorField>
            </div>
            <div className="px-5 py-4 border-t border-slate-200 flex justify-end gap-2">
              <Button variant="outline" onClick={() => setOpenEditor(false)}>Cancel</Button>
              <Button className="bg-[#3096DA] text-white hover:bg-[#277FB8]" onClick={addEvent}>Save</Button>
            </div>
          </div>
        </div>
      )}

      {detailEvent && (
        <div className="fixed right-5 bottom-5 z-50 w-[320px] rounded-2xl border border-slate-200 bg-white p-4 shadow-2xl">
          <div className="flex items-center justify-between">
            <div className="text-sm font-bold text-slate-800">{detailEvent.title}</div>
            <button onClick={() => setDetailId(null)} className="text-slate-500">x</button>
          </div>
          <div className="mt-2 text-xs text-slate-500">{detailEvent.type} • {detailEvent.priority}</div>
          <div className="mt-2 text-xs text-slate-600">{detailEvent.startDate.toLocaleString()}</div>
          <div className="mt-3 flex gap-2">
            <Button variant="outline" className="h-8 px-3 text-xs" onClick={() => setOpenEditor(true)}>Edit</Button>
            <Button className="h-8 px-3 text-xs bg-emerald-600 text-white hover:bg-emerald-700" onClick={() => setEvents((prev) => prev.map((e) => e.id === detailEvent.id ? { ...e, status: "completed" } : e))}>Mark completed</Button>
          </div>
        </div>
      )}
    </div>
  )
}

function Filter({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: string[] }) {
  return (
    <div>
      <label className="mb-1 block text-[0.68rem] font-semibold uppercase tracking-[0.08em] text-slate-500">{label}</label>
      <select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm text-slate-700">
        {options.map((o) => <option key={o} value={o}>{o}</option>)}
      </select>
    </div>
  )
}

function EditorField({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="mb-1 block text-[0.68rem] font-semibold uppercase tracking-[0.08em] text-slate-500">{label}</span>
      {children}
    </label>
  )
}

function Widget({ title, value }: { title: string; value: number }) {
  return (
    <div className="rounded-2xl bg-white p-4 shadow-[0_8px_24px_rgba(31,53,73,0.08)]">
      <div className="text-xs font-bold uppercase tracking-[0.08em] text-slate-600">{title}</div>
      <div className="mt-2 text-2xl font-bold text-slate-800">{value}</div>
    </div>
  )
}
